### ISSUE TITLE
Add state overlap optimisation to measure expressivity of circuits

### ISSUE THREAD

**Issue by AdamSmith-physics** [JamieMair/QuantumCircuits.jl#17]
**First Pass**
- [x] Test Dense vs Sparse eigensolvers
- [x] Use Jamie's sparse Hamiltonian creation
- [x] Get ground state as vector
- [x] Implement basic circuit to state evaluation
- [x] Implement Polar Decomposition based overlap optimisation
- [x] Tidy up and add progress bar

**Second Pass**

There is a big issue with compilation times when splitting a state vector into a tensor and using this for contraction. Try using MPS instead where all of the tensor will be rank 2, 3 or 4 at most.

- [x] Fix some aspects of MatrixProductStates and merge to main
- [x] Implement state vector to MPS function (MatrixProductState)
- [x] Implement MPS version of circuit to state evaluation
- [x] Implement MPS version of Polar Decomposition based overlap optimisation
- [x] Try using SparseArrayKit to produce sparse Hamiltonian from MPO construction.

**Comment by AdamSmith-physics** [comment]
Compilation times are a killer using TensorOperations. As you go to larger system sizes, you have to convert the state to a high-rank tensor and the higher the rank the longer the compilation times for some reason!

It took 1163 seconds to compile for N=16, and only 69 seconds to perform 500 iterations with M=4! This is ridiculous!

Might have to move to an exact MPS representation in order to reach larger system sizes. Then the tensors will all be rank-3.

**Comment by AdamSmith-physics** [comment]
**Second Pass**
- [ ] Use Jamie's sparse Hamiltonian creation
- [ ] Use SparseArrayKit + MPO construction to get full sparse Hamiltonian.
- [ ] Get ground state as vector
- [ ] Implement Polar decomposition based optimisation for full circuit
- [ ] Decompose GS into an MPS
- [ ] Implement Polar decomposition based optimisation for MPS version
- [ ] Use MPS optimisation at initial state for full optimisation (Is there any improvement?)

**Comment by JamieMair** [comment]
Thanks Adam for this. Is this ready for a PR?

**Comment by AdamSmith-physics** [comment]
Yes, I think so actually. I will raise the request now.
